### ISSUE TITLE
[TYPO] wrong helper function name

### ISSUE THREAD

**Issue by faulancr** [sebastiangreger/kirby3-commentions#1]
in the setup documentation to show comments it says `comments( $page, $kirby, $pages );` it has to be `commentions( $page, $kirby, $pages );`

**Comment by sebastiangreger** [comment]
@faulancr I hope you don't mind me pinging you here in a slightly off-topic manner, but I'd like to draw your attention to my update that I am no longer able to maintain the Commentions plugin in the future [→ details here](https://github.com/sebastiangreger/kirby3-commentions/issues/151).
