### ISSUE TITLE
Replace form.php snippet

### ISSUE THREAD

**Issue by yoanmalie** [sebastiangreger/kirby3-commentions#118]
Hi again,

In the 2.0 beta 2 version, I can reuse all of the snippets but I can't reuse the form.php one. Nothing happen when I do some changes (It's just about tags and attributes). No custom configuration, just tried to reuse snippets for this time.
Reused snippets are all placed at the `/site/snippets/commentions/` folders.

What I'm missing here? Thanks!

**Comment by sebastiangreger** [comment]
Great catch, thank you! There was a tiny bug; this is now fixed on the `develop` branch and will be included in beta 3.
