### ISSUE TITLE
Make available via Composer

### ISSUE THREAD

**Issue by sebastiangreger** [sebastiangreger/kirby3-commentions#12]

**Comment by fabianmichael** [comment]
@sebastiangreger Do you need help with that? I could easily transfer the necessary composer.json data from my other plugins and also integrate composer’s autoloder, if you want me to. If you want to take this as an opportunity to learn it yourself, please don’t feel offended by my offer. ;-)

**Comment by sebastiangreger** [comment]
@fabianmichael By all means go ahead with this as you see fit, especially if you do any Purifier magic from #30 anyways.

I tried to read up on it, but I am not sure will using composer be possible while we are not on the repo's main branch, yet - when I set up the plugin on Packagist, it would likely pull the master branch?

**Comment by fabianmichael** [comment]
@sebastiangreger I will tacke #30, once the array-to-object branch has been merged into dev, so it won’t grow to big. Unfortunately, I never published anything on Packagist so far, so I don’t have a clue about how this goes. Maybe someone from the Kirby community can help with that, once we reach 1.0.0-final.

**Comment by sebastiangreger** [comment]
Yes, if the composer/packagist part is not an obstacle during development, my preference would be to get some advice during the go-live process.

**Comment by sebastiangreger** [comment]
Important to observe #33 and #34 when updating the libraries: I recall that at least with either of them there was some reason I did not include the very latest version at the time...
