### ISSUE TITLE
Streamline code and documentation for overriding specific UI strings

### ISSUE THREAD

**Issue by luce-carevic** [sebastiangreger/kirby3-commentions#127]
Hello!

Thank you for this amazing plugin. The work on the documentation is great and very helpful for a beginner like me who does not code but tinker. 

I also really like the philosophy behind.

I’m playing with the last beta version.

I’ve tried to override some UI strings and succeeded with the documentation but cannot understand what is the syntax for UI strings like:  `snippet.form.name.optional`, `snippet.form.help.title` or `feedback.comment.queued`.

I thought it might be something like this:

```
<?= commentions('feedback', [
  't' => [
    'fr' => [
      'comment', [
       'queued' => 'custom UI string'
       ],
      ],
  ]
]) ?>
```

But obviously I'm wrong and missing something.

Could you add an example for these cases in the documentation? I am guessing people like me will also get stucked.

**Comment by sebastiangreger** [comment]
Thank you for your feedback! :slightly_smiling_face:

Overriding strings via the `t`-array the `$attrs` of the frontend helpers indeed is a little wonky, still. There are one or two bugs lingering around, but overall this is still not quite mature as a concept (plus, documentation needs improvement once the code is finalized).

For the time being, it should be possible to override any of those strings using the `config.php` technique, i.e. defining the strings like:

`'sgkirby.commentions.t.fr.snippet.form.help.title' => 'Help title',`

**Comment by luce-carevic** [comment]
You're welcome.

Thanks! I'll try and continue to play with the plugin a bit :)

**Comment by sebastiangreger** [comment]
@luce-carevic I hope you don't mind me pinging you here in a slightly off-topic manner, but I'd like to draw your attention to my update that I am no longer able to maintain the Commentions plugin in the future [→ details here](https://github.com/sebastiangreger/kirby3-commentions/issues/151).
