### ISSUE TITLE
Missing documentation for Twitter webmentions

### ISSUE THREAD

**Issue by MaluNoPeleke** [sebastiangreger/kirby3-commentions#129]
I have installed and configured kirby3-commentions and I am really glad that it exists and is well-documented but I miss an explanation for how to show Twitter replies as a webmention.
I found out about brid.gy and connected my Twitter account there but then it seems as if it relies on a h-feed which I don't know how to serve with Kirby.

**Comment by sebastiangreger** [comment]
Hi. Thanks for reaching out! Always great to hear that the work we put into this is of value…

The "h-feed" expected by brid.gy requires Microformat markup in your frontend template. I.e. the template of the page listing your blog posts has to use a distinct structure of HTML elements and class attributes to be machine-readable as an h-feed. For details see https://indieweb.org/h-feed or http://microformats.org/wiki/h-feed – for validating markup to be a valid h-feed, I personally like https://micrometa.jkphl.is/ but the step-by-step guidance into the Indieweb on https://indiewebify.me/ might be more approachable if this is new territory.

Commentions supports webmentions as defined in the [W3C Specification](https://www.w3.org/TR/webmention/). So-called [backfeed](https://indieweb.org/backfeed) mechanisms like brid.gy build on top of that specification, polling social media services for reactions and turning them into something I’d call “proxy webmentions”:

1. Brid.gy detects that somebody replied to your tweet in which you linked to an article on your website

2. Brid.gy creates a page at a URL like `https://brid-gy.appspot.com/like/twitter/username/1234567890123445678/1234567890123456789` that “pretends” to be a Webmention of the article on your website, even though it actually is a proxy copy of a “like” on Twitter

3. Brid.gy sends this webmention to your website

4. The Commentions plugin treats URL `https://brid-gy.appspot.com/like/twitter/username/1234567890123445678/1234567890123456789` as a webmention of your article and displays it accordingly (and correctly as per the webmention specification: the source of the webmention is indeed at URL `https://brid-gy.appspot.com/…` – the association with the Tweet that triggered the creation of that proxy page is not part of the standard)

To present proxied webmentions in another way, you would have to write your own presentation logic using the plugin’s page methods etc. Commentions (["opinionated but flexible"](https://sebastiangreger.net/2020/06/commentions-comments-and-data-ethics/)) does not provide specific support for proxied backfeed mechanisms out-of-the-box, as I have [strong ethical and legal concerns](https://sebastiangreger.net/2018/05/indieweb-privacy-challenge-webmentions-backfeeds-gdpr) regarding this practice: the way I look at it, unsuspecting Twitter users are subjected to opaque data processing, are not informed, not asked for consent, can’t edit or delete their data, have no means to opt-out, etc. – in my opinion violating key principles of privacy-by-design, possibly also clashing with the GDPR and the Twitter API's ToS (#IANAL, though). Opinions on this of course differ within the community, but that is my position.

**Comment by MaluNoPeleke** [comment]
Thanks a lot, I added the mentioned microformat to my website and will give it a try.

**Comment by MaluNoPeleke** [comment]
I hope that this is a valid h-feed code:

```
<?php snippet('header') ?>

<main>
  <header>
    <h1><?= $page->title() ?></h1>
  </header>


  <div class="h-feed">
    <h1 class="p-name"><a href="<?= $page->url() ?>" class="u-url">Pelekes Blog</a></h1>
    <?php foreach (page('blog')->children()->listed()->flip() as $item): ?>
    <article>
      <header class="article-header h-entry">
      <time><?= $item->date()->toDate('%d.%m.%Y') ?></time>
        <a href="<?= $item->url() ?>" class="u-url">
          <h2 class="p-name"><?= $item->title() ?></h2>
        </a>
      </header>
      <p><?= $item->description() ?></p>
    </article>
    </br>
    <?php endforeach ?>
    <a class="h-card u-url u-uid p-name">Frederik Niedernolte</a>
  </div>

</main>
<?php snippet('footer') ?>
```
