### ISSUE TITLE
Page method usage in an if statement

### ISSUE THREAD

**Issue by MaluNoPeleke** [sebastiangreger/kirby3-commentions#130]
I only want to add an hr element if there are comments for an article.
For this I tried to use the mentioned page method like this:

`if ($page->commentions('approved')) {echo "<hr>";}`

The problem is that it always shows up. Any way to show it only if there are comments on the current page?

**Comment by sebastiangreger** [comment]
`$page->commentions()` returns a [Structure object](https://getkirby.com/docs/reference/objects/cms/structure):

```
if ($page->commentions()->isNotEmpty()) {
    ...
}
```
