### ISSUE TITLE
Replace 3rd party libs with Sane\Html class methods?

### ISSUE THREAD

**Issue by sebastiangreger** [sebastiangreger/kirby3-commentions#131]
With K3.6 sporting a new `Sane\Html` class, it could be investigated whether this could make our use of the html-php5 and HTML Purifier libraries (and thereby the kirby-sanitizer plugin) obsolete by using `sanitize()` to ensure safe HTML.

This is not urgent at all, just adding it to the issue list to keep in mind for further investigation. Nothing wrong with the current solution, but less dependencies and reuse of core classes is of course always nice :) On the other hand, our current implementation may have some advantages in terms of more fine-grained control.

CC @fabianmichael

**Comment by fabianmichael** [comment]
@sebastiangreger I had a quick look at the new `Sane` sanitizer classes. The main reason, why I opted for **HTML Purifier** over other libraries was, that it can correct invalid nesting and allows very fine-grained control over everything. I don’t see that level of detail in Kirby’s Sane classes. The `Sane` classes seem rather basic in comparison and seemingly only do basic filtering for attributes and elements. Without somewhat extensive testing, I’d rather stick with HTML Purifier for the foreseeable future.

**Comment by sebastiangreger** [comment]
@fabianmichael Thanks for taking the time to look into it – much appreciated; I haven't had a chance, yet.

I remember the amount of thought put into this choice from when we first created Commentions and fully agree to your assessment: we should keep this as is. It seems that Kirby's internal class is intended for less advanced contexts.

As a bonus idea, it could be considered to fall back to `Sane` if the HTML Purifier lib is missing (i.e. when installed manually without the companion plugin). Not sure does this provide much value, though, so just dropping this here as a raw thought. But probably only adds more complexity rather than keeping it as simple as possible.

**Comment by fabianmichael** [comment]
@sebastiangreger As `Sane` does not really provide the level of security we were aiming for, I’d also prefer to keep it as it currently is. I’ve read in some other issue that you were planning to add image support to Commentions, so we will probably have to update the code anyway. Taking care of two different implementations is actually nothing I’m very excited about.

**Comment by sebastiangreger** [comment]
@fabianmichael 100% agree. Case closed :slightly_smiling_face:
