### ISSUE TITLE
Support fingerprint plugin if available

### ISSUE THREAD

**Issue by MaluNoPeleke** [sebastiangreger/kirby3-commentions#132]
Can you add support for the[ fingerprint plugin](https://github.com/bnomei/kirby3-fingerprint) if available for commentions('css');?

**Comment by sebastiangreger** [comment]
The `commentions('css')` helper is intended as a first starting point for default websites running on Starterkit. I'd rather not introduce the maintenance overhead to check for the various – to my knowledge at least four – fingerprinting plugins; assumption is that most developers will not use these built-in styles anyway or integrate them into their main style sheet.

I don't know the kirby3-fingerprint plugin (I'm in the [kirby-fingerprint](https://github.com/bvdputte/kirby-fingerprint/) camp myself) first hand but replacing `<?= commentions('css') ?>` with something like `<?= Bnomei\Fingerprint::css('/media/plugins/sgkirby/commentions/styles.css') ?>` should do the trick (the "Commentions CSS helper" really does nothing more than `echo css('media/plugins/sgkirby/commentions/styles.css')`).

If you get it to work, I'd be happy if you could share how; maybe worth including in the Readme as a reference :slightly_smiling_face:

**Comment by MaluNoPeleke** [comment]
Thanks for your explanation. I used your CSS as a basis and added custom style definitions in another file, that's why I was interested.
It works with your one-liner `<?= Bnomei\Fingerprint::css('/media/plugins/sgkirby/commentions/styles.css') ?>` so you can add that to the documentation.
