### ISSUE TITLE
Importing Disqus XML

### ISSUE THREAD

**Issue by MaluNoPeleke** [sebastiangreger/kirby3-commentions#133]
I want to migrate from Disqus to Commentions and wonder if there is an easy way to import the exported XML file from Disqus which looks like this: https://help.disqus.com/en/articles/1717164-comments-export

**Comment by sebastiangreger** [comment]
This can probably be done by writing an import script that somehow loops through the XML and calls the `$page->addCommention()` page method for each comment.
