### ISSUE TITLE
Date formatting does not work with `intl` date handler

### ISSUE THREAD

**Issue by fabianmichael** [sebastiangreger/kirby3-commentions#140]
The current date formatter only works with the `date` and the deprecated `strftime` date handlers, but not the newer `intl` option. https://getkirby.com/docs/reference/system/options/date

https://github.com/sebastiangreger/kirby3-commentions/blob/main/lib/Commention.php#L192-L202

@sebastiangreger Is support for PHP 7.4 still a thing for this plugin? Otherwise, we could rewrite this part using PHP 8’s `match()` here.

**Comment by sebastiangreger** [comment]
Would my minimalist PR fix the issue? (Sorry, no capacity for proper testing right now…)

I would rather not introduce a breaking change re backward compatibility to PHP 7.4 for such a minor bug?!
