### ISSUE TITLE
Could not process comment?

### ISSUE THREAD

**Issue by fillibuster77** [sebastiangreger/kirby3-commentions#149]
Hi,

after setting up the plugin (Download/kirby-sanitizer) I got the following error if I try to send a comment from the frontend:
`Could not process comment. in file site/plugins/kirby3-commentions-main/config/hooks.php`

Something wrong in my configuration?

Best regards!

**Comment by sebastiangreger** [comment]
Hi. I haven't seen or heard of this error before, but can see that the error handling in version 1.x of Commentions is not ideal as it simply throws this Exception.

The most likely reason for this error is that the submitted comment message (text field) is shorter than 4 or longer than 4096 characters. Could this be the reason? If not: does the stack on the error screen give any further indications where things go wrong?

I don't think that the *kirby-sanitizer* plugin has anything to do with it; this is likely either your setup or some strange condition in Commentions causing this; most likely it is the issue described above…

**Comment by fillibuster77** [comment]
Length < 4 was the problem. Thanks :-)

**Comment by sebastiangreger** [comment]
@fillibuster77 I hope you don't mind me pinging you here in a slightly off-topic manner, but I'd like to draw your attention to my update that I am no longer able to maintain the Commentions plugin in the future [→ details here](https://github.com/sebastiangreger/kirby3-commentions/issues/151).
