### ISSUE TITLE
[K4] 4.0 Compatibility

### ISSUE THREAD

**Issue by afbora** [sebastiangreger/kirby3-commentions#155]
> Undefined constant "sgkirby\Commentions\DS"

Kirby 4.0.0-rc.4
PHP 8.1.23

**Comment by sebastiangreger** [comment]
Thank you for checking, and for your note, @afbora !

As announced in Dec 2022, I unfortunately no longer have the resources to keep maintaining this plugin. I archived it today, as it will not be compatible with Kirby 4: ["Sunsetting Commentions", with some pointers on data export, migration to Komments etc.](https://github.com/sebastiangreger/kirby3-commentions/issues/151)
