### ISSUE TITLE
Change to squash commits in main development branch?

### ISSUE THREAD

**Issue by sebastiangreger** [sebastiangreger/kirby3-commentions#19]
Initial plan was to squash all commits from the `dev` branch when later merging 1.0 into `master`, as it contains unnecessarily verbose commit history. Now that there will be significant contributions from @fabianmichael as well, I'd rather see authorship preserved in the master's history.

Before carrying out the agreed collaborative updates: should we squash the current `dev` branch (into a new `develop` branch to be used from then onwards?) and then use (optional/forced?) squash commits by default when merging feature branches into `develop`?

Or what would be the best approach? My primary concern is to preserve authorship credit, secondary concern is to avoid extreme verbosity in the master's commit history (but maybe the latter is not even really a concern?).

**Comment by fabianmichael** [comment]
From my side, it’d be just fine if you squash the commits once 1.0 has been reached. From that point on, we probably expect mostly maintenance releases, so keeping history from that point should not be a problem. Regarding my authorship: We the plugin is released under the MIT, so being able to verifiy my authorship of several parts of the code is nothing I would care about, maybe the simplest way would just be adding me as a contributor to the readme file somewhere next to the 3rd-party libraries.

**Comment by sebastiangreger** [comment]
Alright, let's keep it simple! :smile: Squash into master it is, and readme credits are a matter of course.
