### ISSUE TITLE
Readme: explain how to override built-in translations (if possible?)

### ISSUE THREAD

**Issue by fabianmichael** [sebastiangreger/kirby3-commentions#27]
I realized, that the German translation still has some incosistencies in terms of addressing the visitor. At some places, it’s *Du* (e.g. `Hinterlasse einen Kommentar`), at other places its the formal *Sie* (e.g. `E-Mail (optional; falls Sie eine persönliche Antwort wünschen)`).

For my own usecase, I’d clearly prefer *Du* and I think, for most use-cases this would be the preferred form as well, as the plugin is mostly intended for blogs and personal sites.

@sebastiangreger Should we just stick with *Du* for everything, what do you think?

**Comment by sebastiangreger** [comment]
Agreed: "Du" it shall be :-)

As a matter of fact: I assume it is possible to override these from within the site config or somehow? Couldn't find a quick answer from the forum/docs, but that would be worthwhile including in the readme.

**Comment by fabianmichael** [comment]
I don‘t know, never tried that …

**Comment by sebastiangreger** [comment]
I asked on the forum: https://forum.getkirby.com/t/override-translations-in-plugins/17997

So there is no easy way for developers to override our hardcoded translations. I have a solution in mind for preparing the plugin for overrides; will submit that once we have one main dev branch again.

**Comment by sebastiangreger** [comment]
Implemented and drafted into the readme update - close!
