### ISSUE TITLE
Update Mf2 library / check compatibility when moving to latest version on Composer

### ISSUE THREAD

**Issue by sebastiangreger** [sebastiangreger/kirby3-commentions#33]
`vendor/Mf2/Parser.php` is currently on the version as of 2018-11-20 (commit 10ea6b679c01baa4118beb7f24fe251bf524bfc0).

...tiny changes since then, so not expecting any issues, but worth checking, especially when moving to Composer (#12).

https://github.com/microformats/php-mf2

**Comment by sebastiangreger** [comment]
@fabianmichael Based on a quick test run with the latest Mf2 version: this is fine to update.

**Comment by fabianmichael** [comment]
Closing this, as this has been resolved with #39.
