### ISSUE TITLE
Update php-comments library / check compatibility when moving to latest version on Composer

### ISSUE THREAD

**Issue by sebastiangreger** [sebastiangreger/kirby3-commentions#34]
File `vendor/IndieWeb/comments.php` is on the version of 2015-01-19 (commit b61bc2d8821c714dc9f7fb9a732597e1ade39c5a on Github), with an apparent manual modification (not in the Git history) as follows:

Currently used version:
```php
$short = \str::short($text, $length);
```

Code in the Github repo:
```
$short = ellipsize_to_word($text, $length, '...', 10);
```

Need to check what has been updated since and does it affect the processing of incoming webmentions, especially when moving to the Composer version (#12).

https://github.com/indieweb/php-comments

**Comment by fabianmichael** [comment]
@sebastiangreger Am I getting this right … the `ellipsize_to_word()` function is not part of the php-comments library, is not a native function but called in the php-comments library?

**Comment by sebastiangreger** [comment]
It's a dependency from https://github.com/tantek/cassis - included in the composer.json of php-comments, but not in the original commentions repo. AFAIR I decided against including the Cassis library back in the days, as it does not state a license - so this one-line "hack" made it obsolete.

**Comment by sebastiangreger** [comment]
...no, sorry, I stand corrected:

https://github.com/tantek/cassis/blob/ff854d6dc4a6e4f17134b4b1647ce55492df7e7e/cassis.js#L4

So the reason I did not include it back then was that I was unsure whether code under CC-BY-SA 4.0 can be shipped in a MIT licensed package. Including it via Composer of course solves this (as Tantek's code does not end up in our repo), but would make it impossible to use without Composer?

**Comment by fabianmichael** [comment]
Ahh, also found an wanted to mention the CC-License right now … 😂 Let’s just stick with the local copy for now. I moved it to `includes`, because the vendor folder is not occupied by composer.

**Comment by sebastiangreger** [comment]
> Let’s just stick with the local copy for now. I moved it to `includes`, because the vendor folder is not occupied by composer.

Yes, that is the legally correct way to proceed. php-comments is Apache 2.0 which, AFAIK, is compatible with MIT.

**Comment by fabianmichael** [comment]
I think we should stick with the current version of php-comments for now ("pragmatism"). Maybe open an issue in the repo and ask for removal of the cassis package, if only a single function of that is used. It’s a bit ridcioulous to pull in such a large dependency just for the sake of truncating text. For now, I think we can stick to our custom version.

@sebastiangreger Can we close this for now or do you want to do anything more about the issue?

**Comment by sebastiangreger** [comment]
Done and closed :)
