### ISSUE TITLE
$page->commentions($uid) throws an error

### ISSUE THREAD

**Issue by sebastiangreger** [sebastiangreger/kirby3-commentions#38]
Calling $page->commentions('uo9vcd7bmz') to retrieve a single item by UID throws an error:

TypeError thrown with message "Return value of sgkirby\Commentions\Commentions::get() must be an instance of sgkirby\Commentions\Structure, instance of sgkirby\Commentions\Commention returned"

The culprit seems to be here, but I cannot quite figure out how to fix it:

https://github.com/sebastiangreger/kirby3-commentions/blob/fbc274603ebb3579c071ddec125b1a4284bd6ad3/classes/Commentions.php#L235

**Comment by fabianmichael** [comment]
Solved. Problem was the type hint in the function definition, that required a Commentions Structure to be returned. Just removed the hint and now it works
