### ISSUE TITLE
Cannot change page status when commentions section has error

### ISSUE THREAD

**Issue by sebastiangreger** [sebastiangreger/kirby3-commentions#52]
When the dependencies are missing (the error message about HTML Purifier is shown in the Commentions section), trying to change the status of a draft page to listed fails with this error:

![Screenshot_2020-05-05 11:02](https://user-images.githubusercontent.com/6355217/81050319-1119f400-8ec0-11ea-98e6-5ee3a854ebe8.png)

**Comment by fabianmichael** [comment]
I renamed the computed `errors` value of the section to `commentionsSystemErrors`, so it does not interfere with Kirby itself.  Worked for me after that, please close if it also works for you now.

**Comment by sebastiangreger** [comment]
Works like a charm, thanks!
