### ISSUE TITLE
Data not stored (using bridgy)

### ISSUE THREAD

**Issue by ro-ka** [sebastiangreger/kirby3-commentions#87]
I use [bridgy](https://brid.gy/) to get Twitter activity as webmentions. However, the only thing saved is the source URL, everything else is dropped. I added this to my config and expected it to store text, avatar, website and name, too:

```php
  'sgkirby.commentions.secret' => '------',
  'sgkirby.commentions.templatesWithComments' => ['default', 'photo', 'post', 'project'],
  'sgkirby.commentions.templatesWithWebmentions' => ['default', 'photo', 'post', 'project'],
  'sgkirby.commentions.defaultstatus' => [
    'comment'   => 'pending',
    'like'      => 'approved',
  ],
  'sgkirby.commentions.webmentionfields' => [
    'text',     // store source HTML
    'name',     // store author's realname
    'avatar',   // store author's avatar URL
    'website',  // store author's homepage URL
  ],
  'sgkirby.commentions.hideforms' => true,
```

What is wrong with my setup?

Thanks for creating this library!

**Comment by sebastiangreger** [comment]
Quick check, before I dig deeper: could you please confirm you are running the latest [v1.0.2](https://github.com/sebastiangreger/kirby3-commentions/releases/tag/v1.0.2) of the plugin? (A bugfix release from August, fixing some issues potentially related to what you describe...)

**Comment by ro-ka** [comment]
Sorry, was off for a long weekend: it appears to work after an update. Didn’t check before. Thanks for the great work on this plugin!

**Comment by sebastiangreger** [comment]
That's great to hear :)

**Comment by sebastiangreger** [comment]
@ro-ka I hope you don't mind me pinging you here in a slightly off-topic manner, but I'd like to draw your attention to my update that I am no longer able to maintain the Commentions plugin in the future [→ details here](https://github.com/sebastiangreger/kirby3-commentions/issues/151).

**Comment by ro-ka** [comment]
@sebastiangreger Thanks for the ping and thanks a lot for your work!  🙌
