### ISSUE TITLE
Form is not sent

### ISSUE THREAD

**Issue by timhartmann** [sebastiangreger/kirby3-commentions#94]
I installed the plugin and left everything as it is so far. So I first played around a little. I wrote many comments in a row and noticed that the form is not always submitted. I could not see a pattern. Commentions is only generated if the comment was also sent. However, no comment is output in the frontend, even though the first comment was saved. Can anyone recreate this?

**config.php**
```
'sgkirby.commentions.templatesWithComments' => ['post.text'],
'sgkirby.commentions.templatesWithWebmentions' => ['post.text'],
```

**post.text.php**
```
<?php
  commentions();
?>
```

https://user-images.githubusercontent.com/986401/104094734-0277ae00-5293-11eb-93ce-037142297dd2.mov

**Comment by timhartmann** [comment]
Ich habe herausgefunden, dass es an der Spam Protection liegt.

**Comment by sebastiangreger** [comment]
Good to hear this got resolved!

> I found out that it is due to Spam Protection.

Indeed. And it's not about the amount of comments posted in sequence but probably the [timemin](https://github.com/sebastiangreger/kirby3-commentions/#spam-protection) setting kicking in: unless overridden in your config, Commentions assumes that a meaningful comment cannot humanly be written in under 5 seconds :wink:
